- name: Copy the Service File
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Start Application Service
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: yes
    daemon_reload:  yes
